name: PlatformIO CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Требуется для создания релиза

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PlatformIO Core
        run: |
          pip install --upgrade platformio
          
      - name: Build Project
        run: pio run
     
      - name: Get current date and run ID
        id: get-tag
        run: |
          echo "date=$(date -u +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          echo "tag=${{ github.run_id }}" >> $GITHUB_OUTPUT  # Уникальный ID запуска

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ steps.get-tag.outputs.date }}.${{ steps.get-tag.outputs.tag }}"
          name: "Release ${{ steps.get-tag.outputs.date}} (Build ${{ steps.get-tag.outputs.tag }})"
          files: .pio/build/**/*.hex
          draft: true
          prerelease: true