name: PlatformIO test build

on:
  push:
    branches: [ "main", "testing" ]
  pull_request:
    branches: [ "main", "testing" ]

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PlatformIO Core
        run: |
          pip install --upgrade platformio
          
      - name: Build Project
        run: pio run